### ISSUE TITLE
Unexpected error fetching GS105Ev2 Switch infos data

### ISSUE THREAD

**Issue by adchavira** [ckarrie/ha-netgear-plus#90]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ckarrie/ha-netgear-plus/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

An unexpected error occurs when trying to fetch switch information for the GS105Ev2 model using the netgear_plus integration in Home Assistant. This results in the component failing to retrieve and display the switch data.

### Describe the solution you'd like

I would like the netgear_plus integration to correctly parse and retrieve the switch information for the GS105Ev2 model without encountering the XPath error. The component should handle cases where the expected HTML structure is different, ensuring compatibility with this switch model.

### Describe alternatives you've considered

- Review the HTML structure of the GS105Ev2 model and adjust the XPath to account for any changes in the switch's web page.

- Ensure that the switch's firmware version is compatible with the netgear_plus integration.

- Check the network configuration to make sure there are no connectivity issues between the switch and Home Assistant.

### Additional context

**ha-netgear-plus:** V0.7.6
**Switch Model: Netgear** GS105Ev2
**Bootloader Version:** V1.4.0.5-VB
**Firmware Version:** 1.6.0.15
**Home Assistant Version:** 
- Core 2025.2.2
- Supervisor 2025.02.0
- Operating System14.2

**Traceback (most recent call last):**
  File "/usr/local/lib/python3.13/site-packages/py_netgear_plus/parsers.py", line 35, in get_first_text
    return tree.xpath(xpath)[0].text
           ~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/netgear_plus/__init__.py", line 71, in async_update_switch_infos
    return await gs_switch.async_get_switch_infos()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/netgear_plus/netgear_switch.py", line 93, in async_get_switch_infos
    return await self.hass.async_add_executor_job(self.api.get_switch_infos)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/py_netgear_plus/__init__.py", line 388, in get_switch_infos
    self._get_switch_metadata()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/py_netgear_plus/__init__.py", line 444, in _get_switch_metadata
    switch_metadata | self._page_parser.parse_switch_metadata(page)
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/py_netgear_plus/parsers.py", line 215, in parse_switch_metadata
    switch_serial_number = get_first_text(tree, '//table[@id="tbl1"]/tr[3]/td[2]')
  File "/usr/local/lib/python3.13/site-packages/py_netgear_plus/parsers.py", line 38, in get_first_text
    raise NetgearPlusPageParserError(message) from error
py_netgear_plus.parsers.NetgearPlusPageParserError: XPath //table[@id="tbl1"]/tr[3]/td[2] not found.

**Comment by adchavira** [comment]
When trying to retrieve information from the switch using the get_switch_infos() function, an exception is raised that stops the execution of the code. The error occurs specifically when attempting to retrieve data from an XPath in the parsers.py file.

>>> data = sw.get_switch_infos()
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/py_netgear_plus/parsers.py", line 35, in get_first_text
    return tree.xpath(xpath)[0].text
           ~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/dist-packages/py_netgear_plus/__init__.py", line 388, in get_switch_infos
    self._get_switch_metadata()
  File "/usr/local/lib/python3.11/dist-packages/py_netgear_plus/__init__.py", line 444, in _get_switch_metadata
    switch_metadata | self._page_parser.parse_switch_metadata(page)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/py_netgear_plus/parsers.py", line 215, in parse_switch_metadata
    switch_serial_number = get_first_text(tree, '//table[@id="tbl1"]/tr[3]/td[2]')
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/py_netgear_plus/parsers.py", line 38, in get_first_text
    raise NetgearPlusPageParserError(message) from error
py_netgear_plus.parsers.NetgearPlusPageParserError: XPath //table[@id="tbl1"]/tr[3]/td[2] not found.

**Comment by adchavira** [comment]
In the Chrome Inspector, the tbl1 element is not present. However, tbl2 is available. This might be causing the XPath lookup to fail.

**Comment by foxey** [comment]
Hi @adchavira,

In order to properly fix and test the integration, could you create copies of the following pages from your switch: `login.cgi`, `switch_info.cgi`, `portStatistics.cgi` (or `port_statistics.htm`)? If some of those pages do not exist (404 error or redirect to login or dashboard page), please also try them with the `.htm` suffix.
If you are a bit familiar with Python, the easiest way to get them is to install the `py-netgear-plus` library that the integration is using. Type the following in a terminal or command prompt:
```bash
python -mvenv venv
. ./venv/bin/activate # or in Windows: \venv\Scripts\activate.bat
pip install py-netgear-plus
ngp-cli -dv identify SWITCH_IP_ADDRESS
ngp-cli -dvP YOUR_PASSWORD login SWITCH_IP_ADDRESS
ngp-cli -dv save
ngp-cli -dv logout
```
This will result in a set of pages in a folder called `pages`. Zip them and attach them to this issue. If a prefer to manually save them from your browser, change the suffix to `.txt` before attaching them, as GitHub doesn't allow `.html` or `.cgi` files to be uploaded.

**Comment by adchavira** [comment]
Hi @foxey,

I have attached the requested ZIP file containing the pages from my switch. I followed the steps you provided using the py-netgear-plus library.

Please let me know if you need any additional information or if further testing is required.

Thanks for your guidance and support!



[pages.zip](https://github.com/user-attachments/files/18786040/pages.zip)

**Comment by foxey** [comment]
Hi @adchavira, there are 2 files missing in the zipfile: login.cgi and status.htm (or .cgi?, this is the page with the port speeds and statusses).
Can you share the output of the `ngp-cli` script, so I can see where it bails out?
Also, to speed things up, can you just manually attach the login and port status pages to the issue?

**Comment by adchavira** [comment]
Hi @foxey,
I’ve attached the requested ZIP file along with the output from the script following the new steps. The output can be found in the output.txt file inside the .ZIP.

If you need any additional information or help, feel free to let me know.

[pages.zip](https://github.com/user-attachments/files/18802111/pages.zip)

**Comment by foxey** [comment]
@adchavira It looks like this does the trick! Let me see if I can update the HA integration over the weekend to use the new version of the library. In the meantime, you could manually change the py-netgear-plus version in the manifest file in your HA installation if you like.

**Comment by adchavira** [comment]
It's alive! Thank you so much for your support!

![Image](https://github.com/user-attachments/assets/57e32405-8ebe-480d-9488-ad3fac436616)

**Comment by adchavira** [comment]
I want to report an issue I found with the integration: all sensors specifically related to "received" are consistently showing a value of 0, as indicated in the image.

![Image](https://github.com/user-attachments/assets/4665faa7-843c-4723-83a1-d35bc2f24d62)

**Comment by Arkoxs** [comment]
> [@adchavira](https://github.com/adchavira) It looks like this does the trick! Let me see if I can update the HA integration over the weekend to use the new version of the library. In the meantime, you could manually change the py-netgear-plus version in the manifest file in your HA installation if you like.

Hi @foxey I've change ` "requirements": ["lxml>=4.6.1", "py-netgear-plus==v0.4.5rc0"]` and this works for me.
Also port are reporting correct values.

![Image](https://github.com/user-attachments/assets/0ff504f5-17aa-4a2a-9fb9-2b5067ba22e6)

**Comment by foxey** [comment]
Good to hear! I'll create an official pre-release later this weekend. Trying to squeeze #89 in as well.

**Comment by adchavira** [comment]
Hi @foxey,

I’ve already tried setting everything up from scratch, but the issue still persists.

I noticed that Arkoxs was able to get it working. I’m not sure what was done differently in their case—perhaps it’s related to the firmware versions.

**Comment by foxey** [comment]
@adchavira I've just released v0.7.7 with the fixes to the model and parser definitions. Let me know if it works now!

**Comment by foxey** [comment]
I'll reopen the issue and have a look at the parser. There must still be something wrong. @Arkoxs does it work for you?

**Comment by adchavira** [comment]
I’ve redownloaded, but the issue persists. 


{
  "domain": "netgear_plus",
  "name": "NETGEAR Plus",
  "codeowners": ["@ckarrie", "@foxey"],
  "config_flow": true,
  "documentation": "https://github.com/ckarrie/ha-netgear-plus/blob/main/README.md",
  "iot_class": "local_polling",
  "issue_tracker": "https://github.com/ckarrie/ha-netgear-plus/issues",
  "requirements": ["lxml>=4.6.1", "py-netgear-plus==v0.4.5"],
  "ssdp": [
    {
      "manufacturer": "NETGEAR",
      "deviceType": "urn:schemas-upnp-org:device:InternetGatewayDevice:1"
    }
  ],
  "version": "0.7.7"
}

![Image](https://github.com/user-attachments/assets/39593e0a-fa3a-45ab-ad03-6e6e90712de1)

**Comment by foxey** [comment]
@adchavira I changed the parser to only use the v2 version. Can you use [py-netgear-plus 0.4.6rc0](https://github.com/foxey/py-netgear-plus/releases/tag/v0.4.6rc0) and tell me if that fixes it?

**Comment by foxey** [comment]
I didn't create a new HA integration release yet, so you have to manually update the manifest or try the library on the commandline.

**Comment by adchavira** [comment]
@foxey, With this latest change, I'm now getting data.

Thanks a lot for your support!


![Image](https://github.com/user-attachments/assets/269f5f40-6b00-4e05-a5ad-fe60c1b9897b)

**Comment by adchavira** [comment]
@foxey, I can only check the data from portStatistics.cgi, they are similar to what I'm seeing in Home Assistant, I'm not sure how to verify the other data.

**Comment by foxey** [comment]
> @foxey, I can only check the data from portStatistics.cgi, they are similar to what I'm seeing in Home Assistant, I'm not sure how to verify the other data.

That's what I meant! Thanks! I'll push it in the next release. Is your switch using the most recent firmware?

**Comment by adchavira** [comment]
Bootloader Version | V1.4.0.5-VB
-- | --
Firmware Version | V1.6.0.15

**Comment by Arkoxs** [comment]
This works for me. No issues.

@adchavira I've got:

Bootloader Version V1.6.0.2-VB
Firmware Version V1.6.0.11


Op di 18 feb 2025 17:55 schreef Michiel Fokke ***@***.***>:

**Comment by foxey** [comment]
Fix released in [v0.7.8](https://github.com/ckarrie/ha-netgear-plus/releases/tag/v0.7.8).
